Update packages
voucherifyio/commerce-tools-integration pull request #168
Opened 2024-06-19 08:26 UTC by patricioo1

Removed '^' from package versioning

2024-06-19 14:43 UTC, p-zielinski approved these changes

2024-06-19 14:45 UTC, p-zielinski commented
@patricioo1 dasz radę rozwiązać konflikty? :)

2024-06-19 15:23 UTC, marcinrog commented
jeszcze w package-lock.json

najlepiej zrób to jeszcze raz? tylko tym razem zamiast `npm install --save` użyj `npm install --save-exact`

2024-06-20 06:40 UTC, p-zielinski requested changes
tak jak wyżej + konflikty

2024-06-20 07:00 UTC, marcinrog commented
chyba najprościej będzie Patryku, jak sobie wywalisz node_modules + package-lock.json. potem upewnij się że w package.json (tym bez lock) masz wszystkie dependencies bez exact (~,^) i zrób `npm install` po prostu to sie wygeneruje nowy package-lock.json

2024-06-20 07:02 UTC, p-zielinski commented
Rozwiązałem konflikty, no ale widząc komentarz Marcina zostawię kwestię package-lock-a dla Ciebie :)

2024-06-20 14:24 UTC, patricioo1 commented
przepraszam za małą aktywność tutaj, dzięki Piotrek za rozwiązanie konfliktów, wygenerowałem nowy package-lock

2024-06-20 15:01 UTC, p-zielinski approved these changes

2024-06-20 15:31 UTC, merged