Add product attributes
voucherifyio/commerce-tools-integration pull request #55
Opened 2022-07-28 12:02 UTC by tomek-lochmanczyk-rspective

2022-07-29 06:28 UTC, jkaliszuk requested changes

2022-07-29 06:28 UTC, jkaliszuk commented on src/import/product-import.service.ts
> +
3x the same logic with different schema.related_object variable. Consider wrapping it in the same method e.g in VoucherifyConnectorService.

2022-08-01 08:18 UTC, p-zielinski approved these changes
✔ Customers successfully migrated

2022-08-01 08:23 UTC, p-zielinski requested changes
Unlikely, but I think it may cause error

2022-08-01 08:23 UTC, p-zielinski commented on src/import/customer-import.service.ts
> +    const metadataSchemaProperties = Object.keys(metadataSchema.properties);
const metadataSchemaProperties = Object.keys(metadataSchema?.properties ?? {});

2022-08-01 08:24 UTC, p-zielinski commented on src/import/customer-import.service.ts
> +    const metadataSchemaProperties = Object.keys(metadataSchema.properties);
U can throw an error if `metadataSchema.properties` return `undefined` as well.

2022-08-02 08:24 UTC, p-zielinski reviewed
no further changes requested

2022-08-02 08:28 UTC, jkaliszuk approved these changes

2022-08-03 05:44 UTC, closed without merging